[2024-06-15T19:06:31.747+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:06:31.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:06:31.751+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:06:31.750+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:06:32.515+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:06:32.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:06:32.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:06:32.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.810 seconds
[2024-06-15T19:07:03.051+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:07:03.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:07:03.053+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:07:03.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:07:03.572+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:07:03.564+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:07:03.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:07:03.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.556 seconds
[2024-06-15T19:07:33.953+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:07:33.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:07:33.956+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:07:33.956+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:07:34.445+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:07:34.436+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:07:34.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:07:34.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.521 seconds
[2024-06-15T19:08:04.921+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:08:04.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:08:04.924+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:08:04.923+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:08:05.443+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:08:05.434+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:08:05.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:08:05.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.555 seconds
[2024-06-15T19:08:35.980+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:08:35.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:08:35.984+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:08:35.983+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:08:36.590+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:08:36.581+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:08:36.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:08:36.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.641 seconds
[2024-06-15T19:09:07.135+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:09:07.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:09:07.138+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:09:07.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:09:07.631+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:09:07.622+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:09:07.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:09:07.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.529 seconds
[2024-06-15T19:09:38.119+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:09:38.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:09:38.122+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:09:38.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:09:38.699+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:09:38.688+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:09:38.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:09:38.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.622 seconds
[2024-06-15T19:10:09.825+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:10:09.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:10:09.840+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:10:09.839+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:10:11.349+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:10:11.329+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:10:11.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:10:11.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 1.623 seconds
[2024-06-15T19:10:41.795+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:10:41.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:10:41.806+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:10:41.803+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:10:43.533+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:10:43.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:10:43.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:10:43.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 1.881 seconds
[2024-06-15T19:11:14.656+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:11:14.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:11:14.664+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:11:14.663+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:11:16.063+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:11:16.046+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:11:16.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:11:16.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 1.468 seconds
[2024-06-15T19:11:46.229+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:11:46.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:11:46.233+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:11:46.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:11:47.350+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:11:47.341+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:11:47.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:11:49.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 3.301 seconds
[2024-06-15T19:12:19.730+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:12:19.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:12:19.733+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:12:19.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:12:20.302+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:12:20.293+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:12:20.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:12:22.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 2.835 seconds
[2024-06-15T19:12:52.846+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:12:52.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:12:52.850+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:12:52.850+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:12:59.336+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:12:59.325+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:12:59.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:13:04.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 11.958 seconds
[2024-06-15T19:13:35.458+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:13:35.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:13:35.462+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:13:35.462+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:13:36.189+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:13:36.177+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:13:36.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:13:36.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.775 seconds
[2024-06-15T19:14:06.755+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:14:06.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:14:06.759+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:14:06.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:14:07.502+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:14:07.495+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:14:07.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:14:07.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.884 seconds
[2024-06-15T19:14:37.928+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:14:37.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:14:37.932+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:14:37.932+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:14:38.759+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:14:38.746+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:14:38.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:14:38.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.897 seconds
[2024-06-15T19:15:09.842+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:15:09.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:15:09.845+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:15:09.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:15:11.053+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:15:11.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:15:11.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:15:11.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 1.263 seconds
[2024-06-15T19:15:41.487+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:15:41.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:15:41.490+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:15:41.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:15:42.211+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:15:42.202+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:15:42.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:15:42.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.755 seconds
[2024-06-15T19:16:12.452+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:16:12.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:16:12.462+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:16:12.461+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:16:15.019+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:16:14.993+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:16:15.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:16:15.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 2.645 seconds
[2024-06-15T19:16:45.402+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:16:45.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:16:45.407+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:16:45.405+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:16:46.206+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:16:46.196+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:16:46.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:16:46.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.859 seconds
[2024-06-15T19:17:16.777+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:17:16.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:17:16.784+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:17:16.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:17:17.600+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:17:17.589+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:17:17.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:17:17.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.874 seconds
[2024-06-15T19:17:48.123+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:17:48.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:17:48.128+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:17:48.127+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:17:48.828+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:17:48.817+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:17:48.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:17:48.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.752 seconds
[2024-06-15T19:18:19.456+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:18:19.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:18:19.459+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:18:19.459+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:18:19.992+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:18:19.982+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:18:19.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:18:20.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.568 seconds
[2024-06-15T19:18:50.922+0000] {processor.py:161} INFO - Started process (PID=323) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:18:50.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:18:50.925+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:18:50.924+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:18:51.257+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:18:51.247+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:18:51.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:18:51.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.365 seconds
[2024-06-15T19:19:21.789+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:19:21.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:19:21.792+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:19:21.791+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:19:22.194+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:19:22.185+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:19:22.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:19:22.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.443 seconds
[2024-06-15T19:19:53.266+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:19:53.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:19:53.270+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:19:53.269+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:19:53.623+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:19:53.611+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:19:53.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:19:53.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.391 seconds
[2024-06-15T19:20:24.377+0000] {processor.py:161} INFO - Started process (PID=358) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:20:24.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:20:24.383+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:20:24.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:20:24.852+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:20:24.842+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:20:24.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:20:24.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.529 seconds
[2024-06-15T19:20:55.486+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:20:55.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:20:55.489+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:20:55.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:20:55.870+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:20:55.860+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:20:55.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:20:55.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.440 seconds
[2024-06-15T19:21:26.426+0000] {processor.py:161} INFO - Started process (PID=382) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:21:26.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:21:26.429+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:21:26.428+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:21:26.810+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:21:26.799+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:21:26.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:21:26.838+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.419 seconds
[2024-06-15T19:21:57.459+0000] {processor.py:161} INFO - Started process (PID=394) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:21:57.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:21:57.462+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:21:57.462+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:21:57.861+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:21:57.848+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:21:57.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:21:57.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.459 seconds
[2024-06-15T19:22:28.518+0000] {processor.py:161} INFO - Started process (PID=406) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:22:28.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:22:28.524+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:22:28.523+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:22:28.945+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:22:28.933+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:22:28.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:22:28.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.460 seconds
[2024-06-15T19:22:59.475+0000] {processor.py:161} INFO - Started process (PID=418) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:22:59.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:22:59.478+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:22:59.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:22:59.847+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:22:59.837+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:22:59.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:22:59.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.415 seconds
[2024-06-15T19:23:30.515+0000] {processor.py:161} INFO - Started process (PID=430) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:23:30.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:23:30.518+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:23:30.517+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:23:30.858+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:23:30.848+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:23:30.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:23:30.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.373 seconds
[2024-06-15T19:24:01.377+0000] {processor.py:161} INFO - Started process (PID=442) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:24:01.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:24:01.380+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:24:01.379+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:24:01.814+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:24:01.805+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:24:01.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:24:01.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.482 seconds
[2024-06-15T19:24:32.585+0000] {processor.py:161} INFO - Started process (PID=454) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:24:32.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:24:32.588+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:24:32.588+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:24:32.975+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:24:32.965+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:24:32.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:24:33.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.423 seconds
[2024-06-15T19:25:03.195+0000] {processor.py:161} INFO - Started process (PID=466) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:25:03.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:25:03.198+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:25:03.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:25:03.671+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:25:03.663+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:25:03.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:25:03.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.508 seconds
[2024-06-15T19:25:34.207+0000] {processor.py:161} INFO - Started process (PID=478) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:25:34.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:25:34.211+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:25:34.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:25:34.685+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:25:34.672+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:25:34.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:25:34.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.520 seconds
[2024-06-15T19:26:05.365+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:26:05.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:26:05.370+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:26:05.370+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:26:05.814+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:26:05.802+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:26:05.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:26:05.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.499 seconds
[2024-06-15T19:26:36.046+0000] {processor.py:161} INFO - Started process (PID=503) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:26:36.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:26:36.050+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:26:36.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:26:36.601+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:26:36.586+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:26:36.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:26:36.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.608 seconds
[2024-06-15T19:27:07.023+0000] {processor.py:161} INFO - Started process (PID=515) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:27:07.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:27:07.027+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:27:07.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:27:07.377+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:27:07.368+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:27:07.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:27:07.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.387 seconds
[2024-06-15T19:27:38.046+0000] {processor.py:161} INFO - Started process (PID=527) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:27:38.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:27:38.049+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:27:38.049+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:27:38.453+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:27:38.441+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:27:38.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:27:38.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.445 seconds
[2024-06-15T19:28:08.963+0000] {processor.py:161} INFO - Started process (PID=545) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:28:08.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:28:08.966+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:28:08.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:28:09.379+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:28:09.370+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:28:09.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:28:09.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.453 seconds
[2024-06-15T19:28:39.882+0000] {processor.py:161} INFO - Started process (PID=557) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:28:39.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:28:39.886+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:28:39.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:28:40.240+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:28:40.232+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:28:40.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:28:40.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.391 seconds
[2024-06-15T19:29:10.769+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:29:10.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:29:10.772+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:29:10.772+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:29:11.146+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:29:11.137+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:29:11.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:29:11.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.414 seconds
[2024-06-15T19:29:41.651+0000] {processor.py:161} INFO - Started process (PID=581) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:29:41.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:29:41.658+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:29:41.657+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:29:42.008+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:29:41.999+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:29:42.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:29:42.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.401 seconds
[2024-06-15T19:30:12.738+0000] {processor.py:161} INFO - Started process (PID=593) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:30:12.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:30:12.826+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:30:12.826+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:30:15.298+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:30:15.285+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:30:15.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:30:15.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 2.627 seconds
[2024-06-15T19:30:45.418+0000] {processor.py:161} INFO - Started process (PID=605) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:30:45.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:30:45.423+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:30:45.422+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:30:46.021+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:30:46.008+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:30:46.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:30:46.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.653 seconds
[2024-06-15T19:31:18.345+0000] {processor.py:161} INFO - Started process (PID=620) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:31:18.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:31:18.351+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:31:18.350+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:31:19.125+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:31:19.113+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:31:19.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:31:19.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 1.409 seconds
[2024-06-15T19:31:50.188+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:31:50.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:31:50.191+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:31:50.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:31:50.524+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:31:50.514+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:31:50.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:31:50.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.469 seconds
[2024-06-15T19:32:21.206+0000] {processor.py:161} INFO - Started process (PID=644) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:32:21.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:32:21.212+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:32:21.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:32:21.808+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:32:21.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:32:21.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:32:24.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 2.985 seconds
[2024-06-15T19:32:54.257+0000] {processor.py:161} INFO - Started process (PID=656) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:32:54.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:32:54.260+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:32:54.260+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:32:54.668+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:32:54.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:32:54.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:32:54.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.694 seconds
[2024-06-15T19:33:25.590+0000] {processor.py:161} INFO - Started process (PID=668) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:33:25.591+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:33:25.594+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:33:25.593+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:33:26.208+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:33:26.186+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:33:26.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:33:26.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.681 seconds
[2024-06-15T19:33:56.407+0000] {processor.py:161} INFO - Started process (PID=680) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:33:56.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:33:56.411+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:33:56.410+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:33:56.798+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:33:56.788+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:33:56.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:33:57.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.690 seconds
[2024-06-15T19:34:27.366+0000] {processor.py:161} INFO - Started process (PID=692) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:34:27.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:34:27.369+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:34:27.368+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:34:27.781+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:34:27.769+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:34:27.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:34:28.004+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.644 seconds
[2024-06-15T19:34:58.075+0000] {processor.py:161} INFO - Started process (PID=703) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:34:58.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:34:58.079+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:34:58.078+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:34:58.564+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:34:58.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:34:58.576+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:34:58.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.709 seconds
[2024-06-15T19:35:31.339+0000] {processor.py:161} INFO - Started process (PID=714) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:35:31.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:35:31.343+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:35:31.343+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:35:31.787+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:35:31.778+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:35:31.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:35:37.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 6.515 seconds
[2024-06-15T19:36:08.643+0000] {processor.py:161} INFO - Started process (PID=727) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:36:08.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:36:08.649+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:36:08.648+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:36:09.403+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:36:09.389+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:36:09.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:36:09.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.827 seconds
[2024-06-15T19:36:40.350+0000] {processor.py:161} INFO - Started process (PID=745) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:36:40.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:36:40.357+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:36:40.356+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:36:40.915+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:36:40.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:36:40.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:36:41.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.898 seconds
[2024-06-15T19:37:11.890+0000] {processor.py:161} INFO - Started process (PID=757) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:37:11.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:37:11.894+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:37:11.894+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:37:12.348+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:37:12.339+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:37:12.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:37:12.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.490 seconds
[2024-06-15T19:37:42.580+0000] {processor.py:161} INFO - Started process (PID=769) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:37:42.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:37:42.586+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:37:42.586+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:37:43.067+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:37:43.055+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:37:43.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:37:43.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.527 seconds
[2024-06-15T19:38:13.597+0000] {processor.py:161} INFO - Started process (PID=781) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:38:13.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:38:13.602+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:38:13.601+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:38:14.026+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:38:14.012+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:38:14.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:38:14.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.476 seconds
[2024-06-15T19:38:44.989+0000] {processor.py:161} INFO - Started process (PID=793) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:38:44.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:38:44.992+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:38:44.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:38:45.491+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:38:45.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:38:45.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:38:45.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.541 seconds
[2024-06-15T19:39:16.562+0000] {processor.py:161} INFO - Started process (PID=805) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:39:16.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:39:16.566+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:39:16.566+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:39:17.005+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:39:16.997+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:39:17.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:39:17.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.489 seconds
[2024-06-15T19:39:47.598+0000] {processor.py:161} INFO - Started process (PID=818) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:39:47.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:39:47.602+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:39:47.601+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:39:47.995+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:39:47.984+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:39:48.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:39:48.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.440 seconds
[2024-06-15T19:40:18.618+0000] {processor.py:161} INFO - Started process (PID=830) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:40:18.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:40:18.622+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:40:18.621+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:40:18.967+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:40:18.956+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:40:18.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:40:19.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.407 seconds
[2024-06-15T19:40:49.759+0000] {processor.py:161} INFO - Started process (PID=842) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:40:49.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:40:49.762+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:40:49.762+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:40:50.092+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:40:50.084+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:40:50.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:40:50.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.365 seconds
[2024-06-15T19:41:20.311+0000] {processor.py:161} INFO - Started process (PID=854) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:41:20.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:41:20.314+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:41:20.314+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:41:20.670+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:41:20.660+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:41:20.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:41:20.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.398 seconds
[2024-06-15T19:41:51.406+0000] {processor.py:161} INFO - Started process (PID=866) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:41:51.407+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:41:51.410+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:41:51.409+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:41:51.770+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:41:51.760+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:41:51.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:41:51.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.401 seconds
[2024-06-15T19:42:22.321+0000] {processor.py:161} INFO - Started process (PID=878) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:42:22.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:42:22.325+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:42:22.324+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:42:22.841+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:42:22.826+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:42:22.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:42:22.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.627 seconds
[2024-06-15T19:42:53.612+0000] {processor.py:161} INFO - Started process (PID=891) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:42:53.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:42:53.619+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:42:53.619+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:42:54.198+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:42:54.190+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:42:54.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:42:54.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.643 seconds
[2024-06-15T19:43:24.750+0000] {processor.py:161} INFO - Started process (PID=903) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:43:24.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:43:24.755+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:43:24.754+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:43:25.119+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:43:25.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:43:25.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:43:25.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.440 seconds
[2024-06-15T19:43:55.780+0000] {processor.py:161} INFO - Started process (PID=915) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:43:55.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:43:55.784+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:43:55.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:43:56.183+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:43:56.175+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:43:56.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:43:56.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.453 seconds
[2024-06-15T19:44:26.784+0000] {processor.py:161} INFO - Started process (PID=927) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:44:26.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:44:26.788+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:44:26.787+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:44:27.316+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:44:27.307+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:44:27.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:44:27.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.567 seconds
[2024-06-15T19:44:58.027+0000] {processor.py:161} INFO - Started process (PID=939) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:44:58.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:44:58.031+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:44:58.031+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:44:58.416+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:44:58.406+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:44:58.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:44:58.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.426 seconds
[2024-06-15T19:45:28.975+0000] {processor.py:161} INFO - Started process (PID=951) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:45:28.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:45:28.978+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:45:28.978+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:45:29.335+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:45:29.326+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:45:29.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:45:29.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.398 seconds
[2024-06-15T19:45:59.921+0000] {processor.py:161} INFO - Started process (PID=963) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:45:59.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:45:59.925+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:45:59.924+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:46:00.321+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:46:00.311+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:46:00.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:46:00.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.438 seconds
[2024-06-15T19:46:30.850+0000] {processor.py:161} INFO - Started process (PID=975) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:46:30.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:46:30.854+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:46:30.853+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:46:31.334+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:46:31.321+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:46:31.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:46:31.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.527 seconds
[2024-06-15T19:47:02.077+0000] {processor.py:161} INFO - Started process (PID=987) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:47:02.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:47:02.083+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:47:02.082+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:47:02.661+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:47:02.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:47:02.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:47:02.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.628 seconds
[2024-06-15T19:47:33.280+0000] {processor.py:161} INFO - Started process (PID=1000) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:47:33.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:47:33.283+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:47:33.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:47:33.693+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:47:33.682+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:47:33.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:47:33.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.451 seconds
[2024-06-15T19:48:04.322+0000] {processor.py:161} INFO - Started process (PID=1012) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:48:04.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:48:04.325+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:48:04.324+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:48:04.709+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:48:04.700+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:48:04.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:48:04.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.657 seconds
[2024-06-15T19:48:35.637+0000] {processor.py:161} INFO - Started process (PID=1023) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:48:35.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:48:35.640+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:48:35.639+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:48:36.277+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:48:36.268+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:48:36.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:48:36.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.671 seconds
[2024-06-15T19:49:06.828+0000] {processor.py:161} INFO - Started process (PID=1035) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:49:06.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:49:06.832+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:49:06.831+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:49:07.391+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:49:07.382+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:49:07.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:49:07.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.596 seconds
[2024-06-15T19:49:38.308+0000] {processor.py:161} INFO - Started process (PID=1047) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:49:38.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:49:38.312+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:49:38.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:49:39.132+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:49:39.121+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:49:39.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:49:39.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.867 seconds
[2024-06-15T19:50:09.733+0000] {processor.py:161} INFO - Started process (PID=1059) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:50:09.734+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:50:09.736+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:50:09.736+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:50:10.385+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:50:10.360+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:50:10.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:50:10.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.689 seconds
[2024-06-15T19:50:40.941+0000] {processor.py:161} INFO - Started process (PID=1071) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:50:40.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:50:40.946+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:50:40.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:50:42.344+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:50:42.295+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:50:42.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:50:42.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 1.509 seconds
[2024-06-15T19:51:13.251+0000] {processor.py:161} INFO - Started process (PID=1090) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:51:13.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:51:13.259+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:51:13.259+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:51:13.955+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:51:13.945+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:51:13.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:51:13.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.741 seconds
[2024-06-15T19:51:44.789+0000] {processor.py:161} INFO - Started process (PID=1102) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:51:44.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:51:44.793+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:51:44.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:51:45.444+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:51:45.433+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:51:45.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:51:45.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.695 seconds
[2024-06-15T19:52:16.061+0000] {processor.py:161} INFO - Started process (PID=1114) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:52:16.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:52:16.068+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:52:16.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:52:17.380+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:52:17.368+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:52:17.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:52:17.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 1.375 seconds
[2024-06-15T19:52:47.993+0000] {processor.py:161} INFO - Started process (PID=1126) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:52:47.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:52:47.997+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:52:47.996+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:52:48.565+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:52:48.557+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:52:48.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:52:48.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.605 seconds
[2024-06-15T19:53:19.204+0000] {processor.py:161} INFO - Started process (PID=1138) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:53:19.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:53:19.207+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:53:19.207+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:53:19.753+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:53:19.745+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:53:19.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:53:19.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.579 seconds
[2024-06-15T19:53:50.364+0000] {processor.py:161} INFO - Started process (PID=1150) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:53:50.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:53:50.367+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:53:50.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:53:51.207+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:53:51.195+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:53:51.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:53:51.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.892 seconds
[2024-06-15T19:54:21.764+0000] {processor.py:161} INFO - Started process (PID=1162) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:54:21.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:54:21.768+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:54:21.767+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:54:22.274+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:54:22.264+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:54:22.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:54:22.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.541 seconds
[2024-06-15T19:54:52.842+0000] {processor.py:161} INFO - Started process (PID=1174) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:54:52.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:54:52.845+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:54:52.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:54:53.510+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:54:53.495+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:54:53.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:54:53.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.714 seconds
[2024-06-15T19:55:24.080+0000] {processor.py:161} INFO - Started process (PID=1186) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:55:24.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:55:24.083+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:55:24.083+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:55:24.650+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:55:24.641+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:55:24.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:55:24.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.602 seconds
[2024-06-15T19:55:55.174+0000] {processor.py:161} INFO - Started process (PID=1198) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:55:55.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:55:55.178+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:55:55.177+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:55:55.699+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:55:55.690+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:55:55.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:55:55.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.557 seconds
[2024-06-15T19:56:26.182+0000] {processor.py:161} INFO - Started process (PID=1211) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:56:26.183+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:56:26.186+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:56:26.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:56:26.744+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:56:26.735+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:56:26.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:56:26.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.594 seconds
[2024-06-15T19:56:57.366+0000] {processor.py:161} INFO - Started process (PID=1223) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:56:57.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:56:57.370+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:56:57.369+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:56:58.013+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:56:57.998+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:56:58.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:56:58.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.695 seconds
[2024-06-15T19:57:28.540+0000] {processor.py:161} INFO - Started process (PID=1235) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:57:28.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:57:28.543+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:57:28.543+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:57:29.014+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:57:29.003+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:57:29.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:57:29.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.504 seconds
[2024-06-15T19:57:59.581+0000] {processor.py:161} INFO - Started process (PID=1248) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:57:59.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:57:59.585+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:57:59.584+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:58:00.189+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:58:00.174+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:58:00.203+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:58:00.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.670 seconds
[2024-06-15T19:58:30.867+0000] {processor.py:161} INFO - Started process (PID=1260) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:58:30.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:58:30.870+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:58:30.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:58:31.427+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:58:31.418+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:58:31.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:58:31.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.596 seconds
[2024-06-15T19:59:02.034+0000] {processor.py:161} INFO - Started process (PID=1272) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:59:02.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:59:02.037+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:59:02.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:59:02.657+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:59:02.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:59:02.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:59:02.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.659 seconds
[2024-06-15T19:59:33.301+0000] {processor.py:161} INFO - Started process (PID=1284) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:59:33.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T19:59:33.305+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:59:33.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:59:34.070+0000] {logging_mixin.py:188} INFO - [2024-06-15T19:59:34.056+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T19:59:34.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T19:59:34.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.820 seconds
[2024-06-15T20:00:04.978+0000] {processor.py:161} INFO - Started process (PID=1299) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:00:04.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:00:04.982+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:00:04.981+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:00:05.445+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:00:05.436+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:00:05.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:00:05.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.498 seconds
[2024-06-15T20:00:35.990+0000] {processor.py:161} INFO - Started process (PID=1311) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:00:35.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:00:35.993+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:00:35.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:00:36.559+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:00:36.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:00:36.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:00:36.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.615 seconds
[2024-06-15T20:01:07.082+0000] {processor.py:161} INFO - Started process (PID=1322) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:01:07.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:01:07.085+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:01:07.085+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:01:07.591+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:01:07.581+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:01:07.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:01:07.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.539 seconds
[2024-06-15T20:01:38.198+0000] {processor.py:161} INFO - Started process (PID=1334) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:01:38.199+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:01:38.201+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:01:38.201+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:01:38.712+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:01:38.700+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:01:38.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:01:38.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.549 seconds
[2024-06-15T20:02:09.268+0000] {processor.py:161} INFO - Started process (PID=1346) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:02:09.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:02:09.272+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:02:09.272+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:02:10.045+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:02:10.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:02:10.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:02:10.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.829 seconds
[2024-06-15T20:02:40.593+0000] {processor.py:161} INFO - Started process (PID=1358) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:02:40.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:02:40.597+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:02:40.597+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:02:41.332+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:02:41.321+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:02:41.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:02:41.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.786 seconds
[2024-06-15T20:03:11.897+0000] {processor.py:161} INFO - Started process (PID=1370) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:03:11.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:03:11.901+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:03:11.901+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:03:12.434+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:03:12.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:03:12.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:03:12.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.574 seconds
[2024-06-15T20:03:42.998+0000] {processor.py:161} INFO - Started process (PID=1388) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:03:42.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:03:43.001+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:03:43.001+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:03:43.612+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:03:43.604+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:03:43.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:03:43.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.646 seconds
[2024-06-15T20:04:14.184+0000] {processor.py:161} INFO - Started process (PID=1400) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:04:14.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:04:14.188+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:04:14.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:04:14.698+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:04:14.690+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:04:14.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:04:14.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.545 seconds
[2024-06-15T20:04:45.228+0000] {processor.py:161} INFO - Started process (PID=1413) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:04:45.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:04:45.231+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:04:45.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:04:45.711+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:04:45.702+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:04:45.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:04:45.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.512 seconds
[2024-06-15T20:05:16.205+0000] {processor.py:161} INFO - Started process (PID=1425) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:05:16.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:05:16.208+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:05:16.208+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:05:16.715+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:05:16.706+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:05:16.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:05:16.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.550 seconds
[2024-06-15T20:05:47.129+0000] {processor.py:161} INFO - Started process (PID=1437) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:05:47.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:05:47.131+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:05:47.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:05:47.662+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:05:47.652+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:05:47.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:05:47.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.564 seconds
[2024-06-15T20:06:18.528+0000] {processor.py:161} INFO - Started process (PID=1449) to work on /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:06:18.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl_team_dags.py for tasks to queue
[2024-06-15T20:06:18.533+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:06:18.532+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:06:19.112+0000] {logging_mixin.py:188} INFO - [2024-06-15T20:06:19.100+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/crawl_team_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl_team_dags.py", line 435, in <module>
    step_start >> crawl_data >> [crawl_shotmap, crawl_match_event, crawl_match_incidents,
                                 ^^^^^^^^^^^^^
NameError: name 'crawl_shotmap' is not defined
[2024-06-15T20:06:19.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl_team_dags.py
[2024-06-15T20:06:19.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl_team_dags.py took 0.618 seconds
