[2024-07-27T13:25:49.451+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-27T13:25:49.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_SofaScore_Matchday_daily.crawl_shotmap scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2024-07-27T13:25:49.800+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_SofaScore_Matchday_daily.crawl_shotmap scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2024-07-27T13:25:49.801+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-27T13:25:56.213+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crawl_shotmap> on 2023-08-01 00:00:00+00:00
[2024-07-27T13:25:56.300+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=157) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-27T13:25:56.337+0000] {standard_task_runner.py:63} INFO - Started process 191 to run task
[2024-07-27T13:25:56.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_SofaScore_Matchday_daily', 'crawl_shotmap', 'scheduled__2023-08-01T00:00:00+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/crawl_dags.py', '--cfg-path', '/tmp/tmpmz8hztn6']
[2024-07-27T13:25:56.413+0000] {standard_task_runner.py:91} INFO - Job 284: Subtask crawl_shotmap
[2024-07-27T13:25:56.872+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_SofaScore_Matchday_daily.crawl_shotmap scheduled__2023-08-01T00:00:00+00:00 [running]> on host fde3e54b98e9
[2024-07-27T13:25:57.394+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyenmduc2407@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_SofaScore_Matchday_daily' AIRFLOW_CTX_TASK_ID='crawl_shotmap' AIRFLOW_CTX_EXECUTION_DATE='2023-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-01T00:00:00+00:00'
[2024-07-27T13:25:57.409+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-27T13:25:58.370+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 2. Status code: 404
[2024-07-27T13:26:00.372+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 0. Status code: 404
[2024-07-27T13:26:02.155+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 2. Status code: 404
[2024-07-27T13:26:04.182+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 3. Status code: 404
[2024-07-27T13:26:06.524+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID -. Status code: 404
[2024-07-27T13:26:08.738+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 0. Status code: 404
[2024-07-27T13:26:10.757+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 8. Status code: 404
[2024-07-27T13:26:12.687+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID -. Status code: 404
[2024-07-27T13:26:14.594+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 0. Status code: 404
[2024-07-27T13:26:16.827+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 1. Status code: 404
[2024-07-27T13:26:17.838+0000] {logging_mixin.py:188} INFO -   match_id  status_code
0        2          404
1        0          404
2        2          404
3        3          404
4        -          404
5        0          404
6        8          404
7        -          404
8        0          404
9        1          404
[2024-07-27T13:26:17.840+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-27T13:26:17.841+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-27T13:26:17.853+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_SofaScore_Matchday_daily, task_id=crawl_shotmap, run_id=scheduled__2023-08-01T00:00:00+00:00, execution_date=20230801T000000, start_date=20240727T132549, end_date=20240727T132617
[2024-07-27T13:26:17.940+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-27T13:26:17.966+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-27T13:26:18.015+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-27T15:19:59.398+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-27T15:19:59.494+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_SofaScore_Matchday_daily.crawl_shotmap scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2024-07-27T15:19:59.543+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_SofaScore_Matchday_daily.crawl_shotmap scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2024-07-27T15:19:59.551+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-27T15:20:00.957+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crawl_shotmap> on 2023-08-01 00:00:00+00:00
[2024-07-27T15:20:00.985+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1772) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-27T15:20:00.995+0000] {standard_task_runner.py:63} INFO - Started process 1800 to run task
[2024-07-27T15:20:01.015+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_SofaScore_Matchday_daily', 'crawl_shotmap', 'scheduled__2023-08-01T00:00:00+00:00', '--job-id', '336', '--raw', '--subdir', 'DAGS_FOLDER/crawl_dags.py', '--cfg-path', '/tmp/tmpyjh65vm_']
[2024-07-27T15:20:01.033+0000] {standard_task_runner.py:91} INFO - Job 336: Subtask crawl_shotmap
[2024-07-27T15:20:01.267+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_SofaScore_Matchday_daily.crawl_shotmap scheduled__2023-08-01T00:00:00+00:00 [running]> on host fde3e54b98e9
[2024-07-27T15:20:01.599+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyenmduc2407@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_SofaScore_Matchday_daily' AIRFLOW_CTX_TASK_ID='crawl_shotmap' AIRFLOW_CTX_EXECUTION_DATE='2023-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-01T00:00:00+00:00'
[2024-07-27T15:20:01.602+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-27T15:20:02.664+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 2. Status code: 404
[2024-07-27T15:20:06.619+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 0. Status code: 404
[2024-07-27T15:20:08.520+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 2. Status code: 404
[2024-07-27T15:20:10.322+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 3. Status code: 404
[2024-07-27T15:20:12.050+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID -. Status code: 404
[2024-07-27T15:20:13.958+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 0. Status code: 404
[2024-07-27T15:20:15.973+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 8. Status code: 404
[2024-07-27T15:20:18.169+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID -. Status code: 404
[2024-07-27T15:20:20.125+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 0. Status code: 404
[2024-07-27T15:20:22.019+0000] {logging_mixin.py:188} INFO - Failed to fetch data for match ID 1. Status code: 404
[2024-07-27T15:20:23.029+0000] {logging_mixin.py:188} INFO -   match_id  status_code
0        2          404
1        0          404
2        2          404
3        3          404
4        -          404
5        0          404
6        8          404
7        -          404
8        0          404
9        1          404
[2024-07-27T15:20:23.230+0000] {logging_mixin.py:188} INFO - Data has been written to the database.
[2024-07-27T15:20:23.232+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-27T15:20:23.234+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-27T15:20:23.244+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_SofaScore_Matchday_daily, task_id=crawl_shotmap, run_id=scheduled__2023-08-01T00:00:00+00:00, execution_date=20230801T000000, start_date=20240727T151959, end_date=20240727T152023
[2024-07-27T15:20:23.304+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-27T15:20:23.327+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-27T15:20:23.331+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-27T16:43:04.384+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-27T16:43:04.495+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_SofaScore_Matchday_daily.crawl_shotmap scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2024-07-27T16:43:04.543+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_SofaScore_Matchday_daily.crawl_shotmap scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2024-07-27T16:43:04.554+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-27T16:43:05.351+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crawl_shotmap> on 2023-08-01 00:00:00+00:00
[2024-07-27T16:43:05.390+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3015) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-27T16:43:05.400+0000] {standard_task_runner.py:63} INFO - Started process 3038 to run task
[2024-07-27T16:43:05.400+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_SofaScore_Matchday_daily', 'crawl_shotmap', 'scheduled__2023-08-01T00:00:00+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/crawl_dags.py', '--cfg-path', '/tmp/tmpmunkzg7c']
[2024-07-27T16:43:05.411+0000] {standard_task_runner.py:91} INFO - Job 394: Subtask crawl_shotmap
[2024-07-27T16:43:05.580+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_SofaScore_Matchday_daily.crawl_shotmap scheduled__2023-08-01T00:00:00+00:00 [running]> on host fde3e54b98e9
[2024-07-27T16:43:05.872+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyenmduc2407@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_SofaScore_Matchday_daily' AIRFLOW_CTX_TASK_ID='crawl_shotmap' AIRFLOW_CTX_EXECUTION_DATE='2023-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-01T00:00:00+00:00'
[2024-07-27T16:43:05.886+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-27T16:43:05.930+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-27T16:43:05.931+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_dags.py", line 363, in crawl_shotmap
    return crawler.shotmap()
           ^^^^^^^^^^^^^^^^^
TypeError: CrawlMatchInfo.shotmap() missing 1 required positional argument: 'list_match_id'
[2024-07-27T16:43:05.972+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_SofaScore_Matchday_daily, task_id=crawl_shotmap, run_id=scheduled__2023-08-01T00:00:00+00:00, execution_date=20230801T000000, start_date=20240727T164304, end_date=20240727T164305
[2024-07-27T16:43:06.007+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-07-27T16:43:06.021+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-07-27T16:43:06.022+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-07-27T16:43:06.053+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-07-27T16:43:06.057+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-07-27T16:43:06.061+0000] {taskinstance.py:879} ERROR - Failed to send email to: nguyenmduc2407@gmail.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_dags.py", line 363, in crawl_shotmap
    return crawler.shotmap()
           ^^^^^^^^^^^^^^^^^
TypeError: CrawlMatchInfo.shotmap() missing 1 required positional argument: 'list_match_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1063, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 877, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3163, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1065, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-07-27T16:43:06.109+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 394 for task crawl_shotmap (CrawlMatchInfo.shotmap() missing 1 required positional argument: 'list_match_id'; 3038)
[2024-07-27T16:43:06.168+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-27T16:43:06.239+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-27T16:43:06.249+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
